version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'

  redis:
    image: redis:3.2

  backend:
    build:
      context: backend/.
    volumes:
      - ../.:/repo
      - backend_bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - mysql
      - redis

volumes:
  backend_bundle:
